<a href="https://colab.research.google.com/github/cieloanne/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have?

In [9]:
import numpy as np
eq1 = np.array([[1,1,1],[1,0,4],[0,0,5]])
eq2 = np.array([[89],[89],[95]])
amt = np.linalg.inv(eq1).dot(eq2)
print(amt)

[[13.]
 [57.]
 [19.]]


### Problem 2. Solve each system:

### 3x - y + z = 5

### 9x - 3y +3z = 15

### -12x +4y -4z = -20 

---



In [15]:
A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)
B = np.array([[5],[15],[-20]])
print(B)
Apinv = np.linalg.pinv(A)
x = Apinv.dot(B)
print(x)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]
[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


### Problem 3. Consider the matrix

### Find the eigenvalue/s

### Find the eigenvectors

In [3]:
import numpy as np
from numpy.linalg import eig

A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A,"\n")
w,v = np.linalg.eig(A) 
print("Eigenvalue/s:\n",w.round(),"\n")
print("Eigenvector/s:\n",v.round())

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

Eigenvalue/s:
 [-1.  3.  2.] 

Eigenvector/s:
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
