<a href="https://colab.research.google.com/github/cieloanne/Linear-Algebra-58019/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Python Program to inverse

In [1]:
import numpy as np
A = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
import numpy as np
A = np.array ([[1,2],[4,7]])
B = (np.linalg.inv(A))
print(B)

[[-7.  2.]
 [ 4. -1.]]


In [3]:
import numpy as np
A = np.array ([[1,2],[4,7]])
invA = (np.linalg.inv(A))
print(invA)

[[-7.  2.]
 [ 4. -1.]]


In [4]:
C = np.dot(A,invA)
print(C)

[[1. 0.]
 [0. 1.]]


In [5]:
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(A)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]


In [6]:
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(A)
B = np.transpose(A)
print(B)


[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]
