<a href="https://colab.research.google.com/github/cieloanne/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 1. Create a Python code that displays a square matrix whose length is 5 

In [15]:
square_matrix = np.identity(5)
print(square_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero 

In [8]:
import numpy as np
upper_triangular_matrix = np.array([[1,2,3],[0,3,1],[0,0,5]])
print(upper_triangular_matrix)

[[1 2 3]
 [0 3 1]
 [0 0 5]]


# Question 3. Create a Python code that displays a square matrix which is symmetrical 

In [22]:
import numpy as np
square_matrix = np.array([[2,4,6,8,10],[1,3,5,7,8],[6,4,2,1,6],[8,7,5,3,1],[10,8,6,4,2]])
print(square_matrix)

[[ 2  4  6  8 10]
 [ 1  3  5  7  8]
 [ 6  4  2  1  6]
 [ 8  7  5  3  1]
 [10  8  6  4  2]]


# Question 4. What is the inverse of matrix C? Show your solution by python coding.

In [3]:
import numpy as np
C = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(C)
inv_C = np.linalg.inv(C)

print(inv_C)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


# Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding.

In [2]:
import numpy as np
C = np.array ([[1,2,3],[2,3,3],[3,4,-2]])

detOfC = np.linalg.det(C)

print("Determinant of the given matrix in Question 4:")
print(int(detOfC))

Determinant of the given matrix in Question 4:
5


# Question 6. Find the roots of the linear equations by showing its python codes 

In [6]:
import numpy as np
Equations = np.array([[5,4,1],
                      [10,9,4],
                      [10,13,15]])

Constants = np.array([[[3.4],
                       [8.8],
                       [19.2]]])

roots = np.linalg.inv(Equations) @ Constants

print("Roots of the linear equations:")
print(roots)

Roots of the linear equations:
[[[0.2]
  [0.4]
  [0.8]]]
