<a href="https://colab.research.google.com/github/cieloanne/Linear-Algebra-58019/blob/main/Practical_Lab_Exam1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Practical Lab Exam 1

In [10]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2],[3,4]])

dot = np.dot(A,B)
sum = np.add(D,D)
S = 2*C

print("A:")
print(dot)
print("\nB:")
print(sum)
print("\nC:")
print(S)

A:
[[22 28]
 [49 64]]

B:
[[2 4]
 [6 8]]

C:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [9]:
import numpy as np

X = np.array([[5],[3],[-1]])

print("Problem 2: ")
print("\nType:")
print(type(X))
print("\nDimension:")
print(X.ndim)
print("\nShape:")
print(X.shape)



Problem 2: 

Type:
<class 'numpy.ndarray'>

Dimension:
2

Shape:
(3, 1)
