<a href="https://colab.research.google.com/github/cieloanne/Linear-Algebra-58019/blob/main/PrelimExam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Prelim Exam

### Question 1

In [3]:
import numpy as np

c = np.eye(4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Question 2

In [7]:
answer = 2*c

print(answer)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


### Question 3

In [5]:
A = np.array([2,7,4])
B = np.array([3,9,8])

cross = np.cross(A,B)
print(cross)

[20 -4 -3]
