<a href="https://colab.research.google.com/github/cieloanne/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.array ([[-5,0],[4,1]])
b= np.array ([[6,-3],[2,3]])
print("Sum of A and B:")
print(a+b)

Sum of A and B:
[[ 1 -3]
 [ 6  4]]


In [2]:
import numpy as np
a = np.array ([[-5,0],[4,1]])
b= np.array ([[6,-3],[2,3]])
print("Difference of B and A:")
print(b-a)

Difference of B and A:
[[11 -3]
 [-2  2]]


In [3]:
import numpy as np
a = np.array ([[-5,0],[4,1]])
b= np.array ([[6,-3],[2,3]])
print("Difference of A and B:")
print(a-b)

Difference of A and B:
[[-11   3]
 [  2  -2]]
